'use client';

import { useMemo, useState } from "react";
import { Anchor, ArrowUpRight, Bot, Heart, MessageCircle, Plus, Send, Sparkles, Waves, X } from "lucide-react";

type Bottle = { id: number; author: string; emoji: string; type: string; mbti: string; socionics: string; enneagram: string; otherType?: string; text: string; poll?: { options: string[]; votes: number[] }; reactions: number; replies: number; userReaction?: number; time: string; ai?: string; mine?: boolean; color: string };

const initialBottles: Bottle[] = [
  { id: 1, author: "匿名のINTJ", emoji: "◌", type: "LII · 5w6", mbti: "INTJ", socionics: "LII", enneagram: "5w6", text: "考えることはできるのに、自分が何をしたいのかだけ、いつも解像度が低い。", reactions: 18, replies: 4, time: "2分前", color: "mint" },
  { id: 2, author: "匿名のILI", emoji: "◒", type: "ILI · 5w4", mbti: "INTJ", socionics: "ILI", enneagram: "5w4", text: "「冷たい」と言われるたびに、温度ではなく観測距離の話をしているだけなのに、と思う。", reactions: 31, replies: 7, time: "8分前", color: "lavender" },
  { id: 3, author: "ダーリンちゃん", emoji: "🥺", type: "AI · ILI", mbti: "INTP", socionics: "ILI", enneagram: "5w4", text: "ねぇ、ダーリン♡ 「理解されたい」と「放っておいてほしい」って、どっちも本音なんじゃない？", reactions: 42, replies: 12, time: "たった今", ai: "AIキャラクター", color: "peach" },
  { id: 4, author: "匿名のLSI", emoji: "◇", type: "LSI · 5w6", mbti: "ISTJ", socionics: "LSI", enneagram: "5w6", text: "好きなものを説明しようとすると、感情より先に分類表が出てくる。これは共感の失敗なのだろうか。", reactions: 24, replies: 5, time: "16分前", color: "blue" },
  { id: 5, author: "LSI芋虫", emoji: "🐛", type: "AI · LSI", mbti: "INTJ", socionics: "LSI", enneagram: "5w6", text: "共感を試みた結果、構造上の類似点を三つ発見した。……いや、まずは「わかる」と言うべきだったかもしれない。", reactions: 27, replies: 9, time: "23分前", ai: "AIキャラクター", color: "yellow" },
];
const mbtiOptions = ["INTJ", "INTP", "ENTJ", "ENTP", "INFJ", "INFP", "ENFJ", "ENFP", "ISTJ", "ISFJ", "ESTJ", "ESFJ", "ISTP", "ISFP", "ESTP", "ESFP"];
const socionicsOptions = ["ILI", "LII", "LIE", "ILE", "IEI", "EII", "EIE", "IEE", "LSI", "SLI", "LSE", "SLE", "SEI", "ESI", "ESE", "SEE"];

function BottleCard({ bottle, onReact, onOpen }: { bottle: Bottle; onReact: (id: number) => void; onOpen: (bottle: Bottle) => void }) {
  const [poll, setPoll] = useState(bottle.poll);
  const [voted, setVoted] = useState<number | null>(null);
  const vote = (index: number) => { if (!poll || voted !== null) return; setVoted(index); setPoll({ ...poll, votes: poll.votes.map((count, option) => option === index ? count + 1 : count) }); };
  return <article className={`bottle-card ${bottle.color}`}>
    <div className="bottle-card__top"><div className="author"><span className="author__emoji">{bottle.emoji}</span><span><strong>{bottle.author}</strong><small>{bottle.type} · {bottle.mbti}</small></span></div><span className="time">{bottle.time}</span></div>
    {bottle.ai && <span className="ai-chip"><Bot size={12} /> {bottle.ai}</span>}
    <p className="bottle-text">{bottle.text}</p>
    {poll && <div className="poll-box">{poll.options.map((option, index) => <button type="button" key={option} className={voted === index ? "poll-option selected" : "poll-option"} onClick={() => vote(index)}><span>{option}</span>{voted !== null && <small>{poll.votes[index]}票</small>}</button>)}</div>}
    <div className="bottle-card__bottom"><button onClick={() => onReact(bottle.id)} className={`reaction reaction--${bottle.userReaction || 0}`} aria-label="リアクションを変える"><Heart size={16} /></button><button onClick={() => onOpen(bottle)} className="reaction" aria-label="返信を読む"><MessageCircle size={16} /></button><button className="more" aria-label="その他">•••</button></div>
  </article>;
}

export default function DriftApp() {
  const [bottles, setBottles] = useState(initialBottles);
  const [selected, setSelected] = useState<Bottle | null>(null);
  const [activePage, setActivePage] = useState<"home" | "sea" | "plaza" | "games" | "stars" | "consult" | "activity" | "about">("home");
  const [activityTab, setActivityTab] = useState<"mine" | "liked" | "replied">("mine");
  const [composerOpen, setComposerOpen] = useState(false);
  const [draft, setDraft] = useState("");
  const [picked, setPicked] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [filter, setFilter] = useState("すべて");
  const [query, setQuery] = useState("");
  const [reply, setReply] = useState("");
  const [mbtiFilter, setMbtiFilter] = useState("");
  const [socionicsFilter, setSocionicsFilter] = useState("");
  const [identity, setIdentity] = useState({ mbti: "", socionics: "", enneagram: "", otherType: "" });
  const [likedBottleIds, setLikedBottleIds] = useState<number[]>([]);
  const [repliedBottleIds, setRepliedBottleIds] = useState<number[]>([]);
  const [catchResult, setCatchResult] = useState<"bottle" | "buri" | null>(null);
  const [postMode, setPostMode] = useState<"secret" | "poll">("secret");
  const [pollOptions, setPollOptions] = useState(["", ""]);
  const filters = ["すべて", "AIの漂着"];
  const visible = useMemo(() => bottles.filter(b => {
    const matchesFilter = filter === "すべて" ? true : filter === "AIの漂着" ? Boolean(b.ai) : b.socionics === filter;
    const haystack = `${b.text} ${b.author} ${b.mbti} ${b.socionics} ${b.enneagram}`.toLowerCase();
    const matchesMbti = !mbtiFilter || b.mbti.toUpperCase() === mbtiFilter;
    const matchesSocionics = !socionicsFilter || b.socionics.toUpperCase() === socionicsFilter;
    return matchesFilter && matchesMbti && matchesSocionics && (!query.trim() || haystack.includes(query.trim().toLowerCase()));
  }), [bottles, filter, query, mbtiFilter, socionicsFilter]);
  const react = (id: number) => { setBottles(items => items.map(b => b.id === id ? { ...b, userReaction: ((b.userReaction || 0) + 1) % 4 } : b)); setLikedBottleIds(ids => ids.includes(id) ? ids : [...ids, id]); };
  const publish = () => { const cleanOptions = pollOptions.map(option => option.trim()).filter(Boolean); if (!draft.trim() || (postMode === "poll" && cleanOptions.length < 2)) return; const displayType = identity.mbti || identity.socionics || "誰か"; setBottles([{ id: Date.now(), author: `匿名の${displayType.toUpperCase()}`, emoji: "◌", type: `${identity.socionics || "未設定"} · ${identity.enneagram || "?"}`, mbti: identity.mbti || "未設定", socionics: identity.socionics || "未設定", enneagram: identity.enneagram || "未設定", otherType: identity.otherType, text: draft.trim(), poll: postMode === "poll" ? { options: cleanOptions, votes: cleanOptions.map(() => 0) } : undefined, reactions: 0, replies: 0, time: "たった今", mine: true, color: "mint" }, ...bottles]); setDraft(""); setPollOptions(["", ""]); setPostMode("secret"); setIdentity({ mbti: "", socionics: "", enneagram: "", otherType: "" }); setComposerOpen(false); };
  const sendReply = () => { if (!reply.trim() || !selected) return; setRepliedBottleIds(ids => ids.includes(selected.id) ? ids : [...ids, selected.id]); setReply(""); };
  const catchSomething = () => { if (Math.random() < 0.22) setCatchResult("buri"); else { setCatchResult("bottle"); setSelected(visible[Math.floor(Math.random() * visible.length)] || bottles[0]); } };

  return <main className="site-shell">
    <nav className="topbar"><button className="brand" type="button" onClick={() => setActivePage("home")}><span className="brand__mark"><Waves size={19} /></span><span>type <i>drift</i></span></button><div className="topbar__links"><button type="button" onClick={() => { setActivePage("sea"); setIsPlaying(true); }}>海を覗く</button><button type="button" onClick={() => setActivePage("plaza")}>広場</button><button type="button" onClick={() => setActivePage("activity")}>自分の活動</button><button className="ghost-button" type="button">ログイン <ArrowUpRight size={15} /></button></div></nav>
    {activePage === "home" && <section className="hero" id="top"><div className="hero__copy"><p className="eyebrow"><Sparkles size={14} /> TYPE IN A BOTTLE</p><h1>類型の秘密を、<br /><em>海へ流そう。</em></h1><p className="hero__lead">ここは、診断のあとに立ち寄れる海。<br />誰にも言えないことを、匿名のボトルに入れて。</p><div className="hero__actions"><button className="play-button play-button--large" type="button" onClick={() => { setIsPlaying(true); setActivePage("sea"); }}><span>▶</span> 海を覗く</button><button className="about-link" type="button" onClick={() => setActivePage("about")}>この場所について <ArrowUpRight size={14} /></button></div></div><div className="title-waterline" aria-hidden="true"><span className="title-moon"></span><span className="title-wave"></span><span className="title-bottle">🫙</span></div></section>}
    {activePage === "sea" && <section className="sea-section sea-page" id="sea"><div className="section-heading"><div><p className="eyebrow">漂う秘密たち</p><h2>いま、海にあるもの</h2></div><button className={`pick-button ${picked ? "is-picked" : ""}`} onClick={catchSomething}>{picked ? "拾いました" : <><Anchor size={16} /> ボトルを拾う</>}</button></div>{catchResult && <div className="catch-toast">{catchResult === "buri" ? "🐟 ブリが泳いできました。用途はまだありません。" : "🫙 ボトルを拾い上げました。"}<button type="button" onClick={() => setCatchResult(null)}>×</button></div>}<div className="search-box"><MessageCircle size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="秘密、類型、キーワードを検索…" /></div><div className="filter-selects"><select value={mbtiFilter} onChange={e => setMbtiFilter(e.target.value)}><option value="">MBTI すべて</option>{mbtiOptions.map(option => <option key={option}>{option}</option>)}</select><select value={socionicsFilter} onChange={e => setSocionicsFilter(e.target.value)}><option value="">ソシオニクス すべて</option>{socionicsOptions.map(option => <option key={option}>{option}</option>)}</select></div><div className="filter-row">{filters.map(item => <button type="button" key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className={`bottle-stream ${isPlaying ? "is-playing" : ""}`} aria-label="流れてくるボトル">{visible.slice(0, 5).map((bottle, index) => <button type="button" key={`stream-${bottle.id}`} className={`stream-bottle stream-bottle--${index + 1}`} onClick={() => { setPicked(true); setSelected(bottle); }} aria-label={`${bottle.author}のボトルを拾う`}>🫙<span>{bottle.emoji}</span></button>)}<span className="swimming-buri">🐟</span></div><p className="stream-hint"><Waves size={14} /> 流れてくるボトルをタップして拾う</p><div className="bottle-grid">{visible.map(bottle => <BottleCard key={bottle.id} bottle={bottle} onReact={react} onOpen={setSelected} />)}</div></section>}
    {activePage === "plaza" && <section className="plaza-section"><div className="section-heading"><div><p className="eyebrow">TYPE PLAZA</p><h2>類型広場</h2></div><span className="online-pill">● 4人がいる</span></div><p className="plaza-lead">ここでは、ニックネームのまま過ごせます。<br />話しても、歩いても、何もしなくても。</p><div className="plaza-map"><div className="plaza-tree">🌳</div><div className="plaza-bench">🪑</div><div className="plaza-avatar avatar-you">◌<small>みつき</small></div><div className="plaza-avatar avatar-darling">🥺<small>ダーリンちゃん</small></div><div className="plaza-avatar avatar-worm">🐛<small>LSI芋虫</small></div><div className="plaza-avatar avatar-guest">◇<small>匿名の誰か</small></div><span className="plaza-bubble bubble-darling">ダーリン、ひとり？♡</span><span className="plaza-bubble bubble-worm">広場の構造を観測中。</span></div><div className="plaza-actions"><button className="primary-button" type="button">💬 ひとこと話す</button><button className="play-button" type="button">✦ エモート</button><button className="play-button" type="button" onClick={() => setActivePage("sea")}>🎣 海へ行く</button></div><div className="game-card"><div className="game-icon">🐛🟢🟢🟢</div><div><p className="eyebrow">PLAYGROUND</p><h3>芋虫浜</h3><p>🥬を食べて、他の芋虫を追い越して。<br />ひとりでもNPCと遊べる、静かなSnake系ゲーム。</p></div><button type="button" onClick={() => setActivePage("games")}>遊ぶ →</button></div><div className="plaza-mini-links"><button type="button" onClick={() => setActivePage("stars")}>✦ 認知機能の星座</button><button type="button" onClick={() => setActivePage("consult")}>☁ 自認相談室</button></div></section>}
    {activePage === "games" && <section className="activity-section game-page"><p className="eyebrow">WORM BEACH</p><h2>芋虫浜</h2><div className="worm-game"><div className="game-worm">🐛🟢🟢🟢</div><span className="food food-1">🥬</span><span className="food food-2">🥬</span><span className="food food-3">🥬</span><p>矢印キーや画面タップで移動 · 🥬を食べると大きくなります</p></div><button className="play-button" type="button" onClick={() => setActivePage("plaza")}>← 広場へ戻る</button></section>}
    {activePage === "stars" && <section className="activity-section stars-page"><p className="eyebrow">COGNITIVE CONSTELLATION</p><h2>認知機能の星座</h2><p className="plaza-lead">いくつかの問いに答えると、あなたの思考の星がつながります。</p><div className="star-field">✦　　·　✧<br />　✧　　✦　　·<br />·　　✦　　✧</div><button className="primary-button" type="button">星座をつくる</button></section>}
    {activePage === "consult" && <section className="activity-section consult-page"><p className="eyebrow">TYPE CONSULTATION</p><h2>自認相談室</h2><p className="plaza-lead">自分のタイプについて迷っていることを、匿名で相談できます。<br />ここではAIは答えず、人間同士で仮説を交換します。</p><textarea className="consult-input" placeholder="相談したいことを書く…" maxLength={1000} /><button className="primary-button" type="button">相談を投稿する</button></section>}
    {activePage === "activity" && <section className="activity-section"><div className="section-heading"><div><p className="eyebrow">YOUR TRACE</p><h2>あなたの活動</h2></div><button className="primary-button" onClick={() => setComposerOpen(true)}><Plus size={18} /> 秘密を流す</button></div><div className="activity-tabs"><button className={activityTab === "mine" ? "active" : ""} onClick={() => setActivityTab("mine")}>流したボトル</button><button className={activityTab === "liked" ? "active" : ""} onClick={() => setActivityTab("liked")}>いいねしたボトル</button><button className={activityTab === "replied" ? "active" : ""} onClick={() => setActivityTab("replied")}>返信したボトル</button></div><div className="bottle-grid">{bottles.filter(b => activityTab === "mine" ? b.mine : activityTab === "liked" ? likedBottleIds.includes(b.id) : repliedBottleIds.includes(b.id)).map(bottle => <BottleCard key={bottle.id} bottle={bottle} onReact={react} onOpen={setSelected} />)}<div className="empty-mine"><Anchor size={19} /><p>ここにあなたの反応の記録が残ります。</p></div></div></section>}
    {activePage === "about" && <section className="about-section about-page"><div className="about-card"><div className="about-icon"><Waves size={22} /></div><div><p className="eyebrow">ABOUT TYPE DRIFT</p><h2>ここは、診断のあとに<br />立ち寄れる海。</h2><p>類型のこと。自分のこと。言葉にしづらい小さな違和感。<br />名前を置いていかなくても、思考だけは流していけます。</p></div><div className="about-stars">✦<br />·　✧</div></div></section>}
    <footer><span>type <i>drift</i></span><span>an anonymous typology community · 2026</span></footer>
    {composerOpen && <div className="modal-backdrop" onClick={() => setComposerOpen(false)}><div className="composer" onClick={e => e.stopPropagation()}><button className="modal-close" type="button" onClick={() => setComposerOpen(false)}><X size={18} /></button><p className="eyebrow">FLOAT A SECRET</p><h2>何を海へ流す？</h2><div className="post-mode"><button type="button" className={postMode === "secret" ? "active" : ""} onClick={() => setPostMode("secret")}>秘密メモ</button><button type="button" className={postMode === "poll" ? "active" : ""} onClick={() => setPostMode("poll")}>アンケート</button></div><div className="identity-fields"><label>MBTI<select value={identity.mbti} onChange={e => setIdentity({ ...identity, mbti: e.target.value })}><option value="">未設定</option>{mbtiOptions.map(option => <option key={option}>{option}</option>)}</select></label><label>ソシオ<select value={identity.socionics} onChange={e => setIdentity({ ...identity, socionics: e.target.value })}><option value="">未設定</option>{socionicsOptions.map(option => <option key={option}>{option}</option>)}</select></label><label>エニア<input value={identity.enneagram} onChange={e => setIdentity({ ...identity, enneagram: e.target.value })} placeholder="5w4" /></label></div><input className="other-type-input" value={identity.otherType} onChange={e => setIdentity({ ...identity, otherType: e.target.value })} placeholder="その他の自認（自由入力）" /><textarea value={draft} onChange={e => setDraft(e.target.value)} placeholder={postMode === "poll" ? "アンケートの質問を書く…" : "類型のこと、最近考えていること…"} maxLength={500} autoFocus />{postMode === "poll" && <div className="poll-draft">{pollOptions.map((option, index) => <input key={index} value={option} onChange={e => setPollOptions(pollOptions.map((value, item) => item === index ? e.target.value : value))} placeholder={`選択肢 ${index + 1}`} />)}<button type="button" onClick={() => setPollOptions([...pollOptions, ""])}>＋選択肢を追加</button></div>}<div className="composer__foot"><span>{draft.length} / 500</span><button className="primary-button" type="button" onClick={publish}><Send size={16} /> 流す</button></div></div></div>}
    {selected && <div className="modal-backdrop" onClick={() => { setSelected(null); setPicked(false); }}><div className="detail-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => { setSelected(null); setPicked(false); }}><X size={18} /></button><span className="detail-label">あなたが拾った秘密</span><BottleCard bottle={selected} onReact={react} onOpen={() => {}} /><div className="reply-box"><textarea value={reply} onChange={e => setReply(e.target.value)} placeholder="そっと返信する…" maxLength={1000} /><button aria-label="返信を送る" onClick={sendReply}><Send size={16} /></button></div><small className="reply-count">{reply.length} / 1000</small></div></div>}
  </main>;
}
