'use client';
import { useCallback,useEffect,useRef,useState } from 'react';

type P={x:number;y:number};
type Drop=P&{id:string;expires:number};
type RemoteSnapshot={at:number;x:number;y:number;dir:P;history:P[];score:number;length:number;isAlive:boolean};
type W={id:string;name:string;emoji:string;body:string;x:number;y:number;dir:P;history:P[];score:number;length:number;isAlive:boolean;isNpc:boolean;spawn?:P;prevX?:number;prevY?:number;receivedAt?:number;snapshots?:RemoteSnapshot[]};
type R={client_key?:string;nickname:string;score:number};
const S=3000,SPEED=5,NPC_SPEED=3.4,NPC_STEP=2,PLAYER_STEP=9,MAX=600,FOOD=30,HIT=20,REMOTE_DELAY=120,REMOTE_BUFFER=8;
const API=process.env.NEXT_PUBLIC_API_URL||'https://type-drift-api.onrender.com';
const WORLD=process.env.NEXT_PUBLIC_WORM_WORLD_URL||'https://type-drift-worm-world.onrender.com';
const WS=`${WORLD.replace(/^https:/,'wss:').replace(/^http:/,'ws:')}/ws`;
const COLORS=['🔵','🟣','🟠','🩷','🟡','🔷'];
const remoteBody=(id:string)=>{let n=0;for(let i=0;i<id.length;i++)n=(n+id.charCodeAt(i)*(i+1))%COLORS.length;return COLORS[n]};
const npcTemplates=[['npc1','LSI芋虫','🐛','🔵'],['npc2','ダーリンちゃん','🥺','🌸'],['npc3','匿名のINTJ','🐛','🟣'],['npc4','匿名のLII','🐛','🟠'],['npc5','匿名のLSI','🐛','🟡'],['npc6','匿名','🐛','🔷']] as const;
const spawnPoints:P[]=[{x:1050,y:1300},{x:1950,y:1300},{x:1300,y:1950},{x:1700,y:1950},{x:950,y:1800},{x:2050,y:1800}];
const dir=():P=>{const a=Math.random()*Math.PI*2;return{x:Math.cos(a),y:Math.sin(a)}};
const makePlayer=(name:string):W=>({id:'player',name:name||'匿名の芋虫',emoji:'🐛',body:'🟢',x:S/2,y:S/2,dir:{x:1,y:0},history:Array.from({length:30},(_,i)=>({x:S/2-i*SPEED,y:S/2})),score:0,length:3,isAlive:true,isNpc:false});
const makeNpc=(i:number,score=0):W=>{const t=npcTemplates[i],s=spawnPoints[i];return{id:t[0],name:t[1],emoji:t[2],body:t[3],x:s.x,y:s.y,spawn:s,dir:dir(),history:Array.from({length:30},()=>({x:s.x,y:s.y})),score,length:3+Math.floor(score/5),isAlive:true,isNpc:true}};

export default function WormGameShared({nickname,onExit}:{nickname:string;onExit:()=>void}){
 const [score,setScore]=useState(0),[state,setState]=useState<'intro'|'playing'|'gameover'>('intro'),[net,setNet]=useState<'connecting'|'connected'|'offline'>('connecting'),[ranking,setRanking]=useState<R[]>([]),[onlinePlayers,setOnlinePlayers]=useState(0),[version,setVersion]=useState(0),[shareMessage,setShareMessage]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),box=useRef<HTMLDivElement>(null),p=useRef<W>(makePlayer(nickname)),npcs=useRef<W[]>(npcTemplates.map((_,i)=>makeNpc(i))),remotes=useRef<Map<string,W>>(new Map()),foods=useRef<P[]>([]),drops=useRef<Drop[]>([]),collectedDrops=useRef<Set<string>>(new Set()),socket=useRef<WebSocket|null>(null),key=useRef(''),raf=useRef(0),last=useRef(0),desired=useRef<P>({x:1,y:0}),pointer=useRef({active:false,lastMove:0}),lastUiUpdate=useRef(0);
 const load=useCallback(async()=>{if(!key.current)return;try{const r=await fetch(`${API}/api/worm/ranking?clientKey=${encodeURIComponent(key.current)}`,{cache:'no-store'});if(r.ok){const d=await r.json();setRanking(Array.isArray(d.scores)?d.scores:[])}}catch{}},[]);
 const send=useCallback(()=>{const ws=socket.current,w=p.current;if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'player',clientId:key.current,name:w.name,emoji:w.emoji,body:w.body,x:w.x,y:w.y,dirX:w.dir.x,dirY:w.dir.y,score:w.score,length:w.length,isAlive:w.isAlive,history:w.history.slice(0,MAX)}))},[]);
 const save=useCallback(async()=>{if(!key.current||p.current.score<=0)return;try{await fetch(`${API}/api/worm/ranking`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientKey:key.current,nickname:p.current.name.slice(0,80),score:p.current.score})})}catch{}},[]);
 const dropCabbages=useCallback((w:W)=>{const count=Math.max(3,Math.min(30,w.length));const now=performance.now();for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,d=10+Math.random()*55;drops.current.push({id:`${w.id}-${now}-${i}-${Math.random()}`,x:Math.max(0,Math.min(S,w.x+Math.cos(a)*d)),y:Math.max(0,Math.min(S,w.y+Math.sin(a)*d)),expires:now+30000})}},[]);
 useEffect(()=>{let k=sessionStorage.getItem('type-drift-worm-tab-key');if(!k){k=crypto.randomUUID();sessionStorage.setItem('type-drift-worm-tab-key',k)}key.current=k;foods.current=Array.from({length:180},()=>({x:Math.random()*S,y:Math.random()*S}));void load()},[load]);
 useEffect(()=>{const t=setInterval(()=>void load(),3000);return()=>clearInterval(t)},[load]);
 useEffect(()=>{const t=setInterval(()=>void save(),3000);return()=>clearInterval(t)},[save]);
 useEffect(()=>{let closed=false,timer:ReturnType<typeof setTimeout>|null=null;const connect=()=>{if(closed)return;setNet('connecting');const ws=new WebSocket(WS);socket.current=ws;ws.onopen=()=>{setNet('connected');send()};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type!=='world')return;setOnlinePlayers(Math.max(0,Number(m.playerCount)||0));const seen=new Set<string>(),now=performance.now();for(const q of m.worms||[]){if(!q?.clientId||q.clientId===key.current)continue;seen.add(q.clientId);const x=Number(q.x)||0,y=Number(q.y)||0,alive=q.isAlive!==false;const old=remotes.current.get(q.clientId);if(old?.isAlive&&q.isAlive===false)dropCabbages({...old,x,y,length:Math.max(3,Number(q.length)||3)});const h=Array.isArray(q.history)&&q.history.length?q.history.map((v:any)=>({x:Number(v.x)||0,y:Number(v.y)||0})):[{x,y}];const snap:RemoteSnapshot={at:now,x,y,dir:{x:Number(q.dirX)||0,y:Number(q.dirY)||0},history:h,score:Number(q.score)||0,length:Math.max(3,Number(q.length)||3),isAlive:alive};const snapshots=[...(old?.snapshots||[]),snap].slice(-REMOTE_BUFFER);remotes.current.set(q.clientId,{id:q.clientId,name:q.name||'匿名の芋虫',emoji:q.emoji||'🐛',body:remoteBody(q.clientId),x,y,prevX:old?.x??x,prevY:old?.y??y,receivedAt:now,dir:snap.dir,history:h,length:snap.length,score:snap.score,isAlive:alive,isNpc:false,snapshots})}remotes.current.forEach((_,id)=>{if(!seen.has(id))remotes.current.delete(id)});drops.current=drops.current.filter(d=>d.expires>now&&!collectedDrops.current.has(d.id));if(now-lastUiUpdate.current>200){lastUiUpdate.current=now;setVersion(v=>v+1)}}catch{}};ws.onclose=()=>{if(!closed){setNet('offline');timer=setTimeout(connect,1000)}};ws.onerror=()=>setNet('offline')};connect();return()=>{closed=true;if(timer)clearTimeout(timer);socket.current?.close()}},[dropCabbages,send]);
 useEffect(()=>{const t=setInterval(send,100);return()=>clearInterval(t)},[send]);
 const camera=useCallback((w:W,dw:number,dh:number)=>{const scale=Math.max(.38,Math.min(1,Math.min(dw/900,dh/600))),vw=dw/scale,vh=dh/scale,cx=vw>=S?S/2:Math.max(vw/2,Math.min(S-vw/2,w.x)),cy=vh>=S?S/2:Math.max(vh/2,Math.min(S-vh/2,w.y));return{scale,ox:dw/2-cx*scale,oy:dh/2-cy*scale}},[]);
 const remoteVisual=useCallback((q:W,now:number)=>{const snaps=q.snapshots||[];if(!snaps.length)return{x:q.x,y:q.y,dir:q.dir,history:q.history};const target=now-REMOTE_DELAY;let a=snaps[0],b=snaps[snaps.length-1];for(let i=0;i<snaps.length-1;i++){if(snaps[i].at<=target&&target<=snaps[i+1].at){a=snaps[i];b=snaps[i+1];break}}if(target>=b.at)return{x:b.x,y:b.y,dir:b.dir,history:b.history};if(target<=a.at)return{x:a.x,y:a.y,dir:a.dir,history:a.history};const t=(target-a.at)/Math.max(1,b.at-a.at);return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,dir:{x:a.dir.x+(b.dir.x-a.dir.x)*t,y:a.dir.y+(b.dir.y-a.dir.y)*t},history:b.history}},[]);
 const draw=useCallback((now=performance.now())=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const w=p.current,r=c.getBoundingClientRect(),dw=Math.max(1,r.width),dh=Math.max(1,r.height),dpr=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(dw*dpr)||c.height!==Math.round(dh*dpr)){c.width=Math.round(dw*dpr);c.height=Math.round(dh*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#a9d9c5';ctx.fillRect(0,0,dw,dh);const{scale,ox,oy}=camera(w,dw,dh),sx=(x:number)=>x*scale+ox,sy=(y:number)=>y*scale+oy;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='27px sans-serif';for(const f of foods.current){const x=sx(f.x),y=sy(f.y);if(x>-40&&x<dw+40&&y>-40&&y<dh+40)ctx.fillText('🥬',x,y)}for(const d of drops.current){const x=sx(d.x),y=sy(d.y);if(x>-40&&x<dw+40&&y>-40&&y<dh+40)ctx.fillText('🥬',x,y)}
 const worm=(q:W,visualOverride?:ReturnType<typeof remoteVisual>)=>{if(!q.isAlive)return;const v=visualOverride||{x:q.x,y:q.y,dir:q.dir,history:q.history};const step=q.isNpc?NPC_STEP:PLAYER_STEP,count=Math.min(Math.max(0,q.length-1),Math.floor((v.history.length-1)/step));ctx.font='25px sans-serif';for(let i=count;i>=1;i--){const pt=v.history[Math.min(i*step,v.history.length-1)];const x=sx(pt.x),y=sy(pt.y);if(x>-35&&x<dw+35&&y>-35&&y<dh+35)ctx.fillText(q.body||'🟢',x,y)}ctx.save();ctx.translate(sx(v.x),sy(v.y));if(v.dir.x>0)ctx.scale(-1,1);ctx.font='34px sans-serif';ctx.fillText(q.emoji,0,0);ctx.restore();ctx.font='10px sans-serif';ctx.fillStyle='#466f71';ctx.fillText(q.name,sx(v.x),sy(v.y)-25)};
 for(const q of npcs.current)worm(q);remotes.current.forEach(q=>worm(q,remoteVisual(q,now)));worm(w)},[camera,remoteVisual]);
 const hitBody=useCallback((head:W,body:W)=>{if(!body.isAlive||head.id===body.id)return false;const step=body.isNpc?NPC_STEP:PLAYER_STEP;const max=Math.min(body.history.length-1,Math.max(0,(body.length-1)*step));for(let i=0;i<=max;i+=step){const pt=body.history[i];if(Math.hypot(head.x-pt.x,head.y-pt.y)<HIT)return true}return false},[]);
 const resetNpc=useCallback((npc:W)=>{const i=npcTemplates.findIndex(t=>t[0]===npc.id);const fresh=makeNpc(i);Object.assign(npc,fresh)},[]);
 const update=useCallback((now:number)=>{const w=p.current,dt=last.current?Math.min(.033,(now-last.current)/1000):0;last.current=now;if(state==='playing'&&w.isAlive){const stopped=pointer.current.active&&now-pointer.current.lastMove>140,target=stopped?{x:0,y:0}:desired.current;if(Math.hypot(target.x,target.y)>0){const turn=Math.min(1,dt*30);w.dir.x+=(target.x-w.dir.x)*turn;w.dir.y+=(target.y-w.dir.y)*turn;const l=Math.hypot(w.dir.x,w.dir.y)||1;w.dir.x/=l;w.dir.y/=l;w.x=Math.max(0,Math.min(S,w.x+w.dir.x*SPEED*(dt*60)));w.y=Math.max(0,Math.min(S,w.y+w.dir.y*SPEED*(dt*60)));w.history.unshift({x:w.x,y:w.y});if(w.history.length>MAX)w.history.pop()}
 let next:P[]=[],eat=0;for(const f of foods.current){if(Math.hypot(f.x-w.x,f.y-w.y)<FOOD)eat++;else next.push(f)}foods.current=next;for(const d of drops.current){if(!collectedDrops.current.has(d.id)&&Math.hypot(d.x-w.x,d.y-w.y)<FOOD){collectedDrops.current.add(d.id);eat++}}while(foods.current.length<180)foods.current.push({x:Math.random()*S,y:Math.random()*S});if(eat){w.score+=eat;w.length=3+Math.floor(w.score/5);setScore(w.score)}
 const localAll=[w,...npcs.current];for(const npc of npcs.current){if(!npc.isAlive)continue;let tx=0,ty=0,bestFood:P|undefined,bestD=Infinity,attack:W|undefined;for(const f of foods.current){const d=Math.hypot(f.x-npc.x,f.y-npc.y);if(d<bestD){bestD=d;bestFood=f}}for(const other of localAll){if(!other.isAlive||other.id===npc.id)continue;const d=Math.hypot(other.x-npc.x,other.y-npc.y);if(other.length<npc.length&&d<650&&!attack)attack=other;if(other.length>npc.length&&d<220){tx+=(npc.x-other.x)/Math.max(1,d)*(1-d/220)*3;ty+=(npc.y-other.y)/Math.max(1,d)*(1-d/220)*3}}if(attack){tx+=attack.x-npc.x;ty+=attack.y-npc.y}else if(bestFood){tx+=bestFood.x-npc.x;ty+=bestFood.y-npc.y}else{tx+=npc.dir.x*100;ty+=npc.dir.y*100}const margin=220;if(npc.x<margin)tx+=(margin-npc.x)*2;if(npc.x>S-margin)tx-=(npc.x-(S-margin))*2;if(npc.y<margin)ty+=(margin-npc.y)*2;if(npc.y>S-margin)ty-=(npc.y-(S-margin))*2;const dl=Math.hypot(tx,ty)||1,dx=tx/dl,dy=ty/dl;npc.dir.x+=(dx-npc.dir.x)*Math.min(.18,dt*4);npc.dir.y+=(dy-npc.dir.y)*Math.min(.18,dt*4);const nl=Math.hypot(npc.dir.x,npc.dir.y)||1;npc.dir.x/=nl;npc.dir.y/=nl;npc.x=Math.max(0,Math.min(S,npc.x+npc.dir.x*NPC_SPEED*(dt*60)));npc.y=Math.max(0,Math.min(S,npc.y+npc.dir.y*NPC_SPEED*(dt*60)));npc.history.unshift({x:npc.x,y:npc.y});if(npc.history.length>MAX)npc.history.pop();let remain:P[]=[],got=0;for(const f of foods.current){if(Math.hypot(f.x-npc.x,f.y-npc.y)<FOOD)got++;else remain.push(f)}foods.current=remain;if(got){npc.score+=got;npc.length=3+Math.floor(npc.score/5)}}
 const collisionTargets=[...npcs.current,...remotes.current.values()];let hit=false;for(const o of collisionTargets){if(hit||!o.isAlive)continue;if(hitBody(w,o))hit=true}if(hit){dropCabbages(w);w.isAlive=false;setState('gameover');void save()}
 for(const npc of npcs.current){if(!npc.isAlive)continue;for(const body of [...npcs.current,w]){if(!body.isAlive||body.id===npc.id)continue;if(hitBody(npc,body)){dropCabbages(npc);npc.isAlive=false;setTimeout(()=>resetNpc(npc),700);break}}}
 }
 drops.current=drops.current.filter(d=>d.expires>now&&!collectedDrops.current.has(d.id));draw(now);raf.current=requestAnimationFrame(update)},[draw,dropCabbages,hitBody,resetNpc,save,state]);
 useEffect(()=>{raf.current=requestAnimationFrame(update);return()=>cancelAnimationFrame(raf.current)},[update]);
 const pointerMove=useCallback((x:number,y:number)=>{const c=canvas.current;if(!c)return;const r=c.getBoundingClientRect(),{scale,ox,oy}=camera(p.current,r.width,r.height),hx=r.left+p.current.x*scale+ox,hy=r.top+p.current.y*scale+oy,dx=x-hx,dy=y-hy,d=Math.hypot(dx,dy);pointer.current={active:true,lastMove:performance.now()};if(d>5)desired.current={x:dx/d,y:dy/d}},[camera]);
 useEffect(()=>{const move=(e:PointerEvent)=>{if(state!=='playing')return;pointerMove(e.clientX,e.clientY);e.preventDefault()},down=(e:PointerEvent)=>{if(state!=='playing')return;pointerMove(e.clientX,e.clientY);try{(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}catch{}},up=()=>{pointer.current.active=false;desired.current={x:0,y:0}};const el=box.current;if(!el)return;el.addEventListener('pointermove',move,{passive:false});el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);return()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerdown',down);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up)}},[pointerMove,state]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{const d={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}}[e.key] as P|undefined;if(d){e.preventDefault();if(state==='intro')start();pointer.current.active=false;desired.current=d}};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[state]);
 const start=()=>{p.current=makePlayer(nickname);npcs.current=npcTemplates.map((_,i)=>makeNpc(i));setScore(0);setShareMessage('');setState('playing');desired.current={x:1,y:0};pointer.current={active:false,lastMove:0};last.current=0;void send()};
 const share=async()=>{const text=`芋虫浜で🥬${p.current.score}個集めた！`;void save();setShareMessage('');try{if(typeof navigator!=='undefined'&&typeof navigator.share==='function'){await navigator.share({title:'芋虫浜',text,url:window.location.href});setShareMessage('共有シートを開きました');return}const value=`${text} ${window.location.href}`;if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value);setShareMessage('共有文をコピーしました');return}const ta=document.createElement('textarea');ta.value=value;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();setShareMessage('共有文をコピーしました')}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;setShareMessage('共有を開けませんでした。もう一度押してみてね') }};
 const live=(()=>{const rows:R[]=[];if(state!=='intro')rows.push({nickname:p.current.name||'あなた',score:p.current.score,client_key:key.current});npcs.current.forEach(w=>{if(w.isAlive)rows.push({nickname:w.name,score:w.score,client_key:`npc:${w.id}`})});remotes.current.forEach(w=>{if(w.isAlive)rows.push({nickname:w.name,score:w.score,client_key:w.id})});rows.sort((a,b)=>b.score-a.score);const top=rows.slice(0,5);const self=rows.find(r=>r.client_key===key.current);return self&&top.every(r=>r.client_key!==key.current)?[...top,self]:top})();
 const past=ranking.slice(0,3);void version;
 return <section className="activity-section game-page">
  {state==='intro'&&<div className="worm-intro"><p className="eyebrow">WORM BEACH</p><div className="worm-intro-icon">🐛🟢🟢</div><h2>芋虫浜</h2><p>静かな海で、好きなだけにょろにょろしよう。</p><div className="worm-intro-rules"><p>🥬を食べるとスコアが増え、5個ごとに身体が伸びます。</p><p>🐛他の芋虫の身体に頭がぶつかると観測終了。</p><p>🤖NPCは誰もいない時も動いています。</p><p>🖱️マウス・指を動かした方向へ進み、止めると停止。</p></div><button className="primary-button" type="button" onClick={start}>芋虫浜へ入る</button></div>}
  {state!=='intro'&&<><p className="eyebrow">WORM BEACH</p><h2>芋虫浜 <small className="score-label">🥬 {score}</small></h2><div className="worm-status"><span>{net==='connected'?'🟢 オンライン':net==='connecting'?'🟡 接続中…':'⚪ 再接続中…'}</span><span>👥 {onlinePlayers}人</span></div><div ref={box} className="worm-game" style={{position:'relative',width:'100%',height:450,overflow:'hidden',background:'#a9d9c5',borderRadius:'12px 30px 30px 30px',touchAction:'none'}}><canvas ref={canvas} style={{display:'block',width:'100%',height:'100%',touchAction:'none'}}/><p className="worm-hint">指やマウスを動かした方向へ進みます · 矢印キーでも操作できます</p>{state==='gameover'&&<div className="worm-result"><div><p className="eyebrow">YOUR RESULT</p><h3>観測終了</h3><div className="result-score">🥬 <b>{score}</b></div><p>集めたキャベツ</p><p>体長：{p.current.length}</p><button className="pick-button" type="button" onClick={start}>もう一度遊ぶ</button><button className="play-button" type="button" onClick={share}>共有する</button>{shareMessage&&<p className="share-message">{shareMessage}</p>}</div></div>}</div></>}
  <div className="worm-below"><div className="worm-ranking"><h3 className="worm-ranking-title">🏆 現在のランキング <small>上位5名＋あなた</small></h3><div className="worm-ranking-list">{live.map((r,idx)=><div key={`${r.client_key||r.nickname}-${idx}`} className={`worm-rank-row${r.client_key===key.current?' is-self':''}${idx===0?' is-first':''}`}><span>{idx+1}.</span><span className="worm-rank-name">{r.nickname}</span><b>{r.score} 🥬</b></div>)}</div>{past.length>0&&<div className="worm-past"><b>過去最多</b>{past.map((r,i)=><span key={`${r.nickname}-${i}`}>{r.nickname} {r.score}🥬</span>)}</div>}</div><div className="worm-actions"><button className="play-button" type="button" onClick={onExit}>← 広場へ戻る</button>{state!=='intro'&&<button className="ghost-button" type="button" onClick={share}>共有</button>}</div></div>
  <style jsx>{`.worm-intro{max-width:560px;margin:20px auto;padding:34px 28px;text-align:center;background:rgba(207,239,229,.65);border-radius:18px}.worm-intro-icon{font-size:36px;margin:18px 0 4px}.worm-intro h2{margin:0;color:#466f71;font-size:30px}.worm-intro>p:not(.eyebrow){color:#6f8d86}.worm-intro-rules{margin:20px 0;text-align:left;padding:16px 18px;background:rgba(255,255,255,.55);border-radius:12px;color:#6f8d86;font-size:12px;line-height:1.8}.worm-intro-rules p{margin:4px 0}.worm-status{display:flex;gap:8px;margin-bottom:8px;font-size:10px;color:#6f8d86}.worm-hint{position:absolute;bottom:16px;left:20px;margin:0;z-index:20;color:#57877c;font-size:9px;pointer-events:none}.worm-result{position:absolute;inset:0;background:rgba(34,56,62,.5);display:grid;place-items:center;z-index:100}.worm-result>div{background:#fffaf1;padding:28px 34px;border-radius:16px;text-align:center;min-width:230px}.worm-result h3{margin:4px 0}.worm-result p{margin:5px;color:#6f8d86}.result-score{font-size:30px;margin:12px 0}.worm-result button{display:block;width:100%;margin-top:8px}.share-message{font-size:10px}.worm-below{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;align-items:start;margin-top:15px}.worm-ranking{min-width:0}.worm-ranking-title{margin:0 0 8px;color:#466f71;font-size:15px;white-space:nowrap}.worm-ranking-title small{font-weight:normal;opacity:.65}.worm-ranking-list{display:grid;gap:4px;font-size:11px;color:#6f8d86}.worm-rank-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:6px;align-items:center;padding:6px 8px;border-radius:7px;background:rgba(255,255,255,.45);min-width:0}.worm-rank-row.is-first{background:rgba(255,242,185,.55)}.worm-rank-row.is-self{background:rgba(207,239,229,.9);box-shadow:inset 3px 0 #55a89b}.worm-rank-row.is-first.is-self{background:rgba(255,242,185,.72);box-shadow:inset 3px 0 #55a89b}.worm-rank-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:700;color:#466f71}.worm-rank-row b{white-space:nowrap}.worm-past{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px;font-size:9px;color:#8ba19f}.worm-actions{display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end}@media(max-width:760px){.worm-below{display:flex;flex-direction:column;gap:12px}.worm-ranking{width:100%}.worm-ranking-title{white-space:nowrap;writing-mode:horizontal-tb}.worm-ranking-list{width:100%}.worm-actions{width:100%;justify-content:flex-start}.worm-actions button{flex:1 1 auto}.worm-game{height:min(450px,calc(100vw * .78))!important;min-height:300px}.worm-intro{margin-top:8px;padding:26px 18px}}`}</style>
 </section>
}
