'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { X } from 'lucide-react';

type P={x:number;y:number};
type W={id:string;name:string;emoji:string;body:string;x:number;y:number;dir:P;history:P[];score:number;length:number;isAlive:boolean;isNpc:boolean;lastSeen:number};
type R={nickname:string;score:number};
const S=3000,SPEED=4,SPACING=6,MAX=600,FOOD=30,HIT=20;
const API=process.env.NEXT_PUBLIC_API_URL||'https://type-drift-api.onrender.com';
const WORLD=process.env.NEXT_PUBLIC_WORM_WORLD_URL||'https://type-drift-worm-world.onrender.com';
const WS=`${WORLD.replace(/^https:/,'wss:').replace(/^http:/,'ws:')}/ws`;
const makePlayer=(name:string):W=>({id:'player',name:name||'匿名の芋虫',emoji:'🐛',body:'🟢',x:S/2,y:S/2,dir:{x:1,y:0},history:Array.from({length:30},()=>({x:S/2,y:S/2})),score:0,length:3,isAlive:true,isNpc:false,lastSeen:Date.now()});

export default function WormGameShared({nickname,onExit}:{nickname:string;onExit:()=>void}){
 const [score,setScore]=useState(0),[state,setState]=useState<'playing'|'gameover'>('playing'),[net,setNet]=useState<'connecting'|'connected'|'offline'>('connecting'),[ranking,setRanking]=useState<R[]>([]),[rules,setRules]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),p=useRef<W>(makePlayer(nickname)),remotes=useRef<Map<string,W>>(new Map()),foods=useRef<P[]>([]),socket=useRef<WebSocket|null>(null),key=useRef(''),raf=useRef<number>(0),lastFrame=useRef(0),box=useRef<HTMLDivElement>(null);
 const load=useCallback(async()=>{try{const r=await fetch(`${API}/api/worm/ranking`,{cache:'no-store'});if(r.ok){const d=await r.json();setRanking(Array.isArray(d.scores)?d.scores:[])}}catch{}},[]);
 const send=useCallback(()=>{const ws=socket.current,w=p.current;if(ws?.readyState===WebSocket.OPEN){ws.send(JSON.stringify({type:'player',clientId:key.current,name:w.name,emoji:w.emoji,body:w.body,x:w.x,y:w.y,dirX:w.dir.x,dirY:w.dir.y,score:w.score,length:w.length,isAlive:w.isAlive,history:w.history.slice(0,MAX)}))}},[]);
 const save=useCallback(async()=>{if(!key.current)return;try{await fetch(`${API}/api/worm/ranking`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientKey:key.current,nickname:p.current.name.slice(0,80),score:p.current.score})})}catch{}},[]);
 useEffect(()=>{let k=sessionStorage.getItem('type-drift-worm-tab-key');if(!k){k=crypto.randomUUID();sessionStorage.setItem('type-drift-worm-tab-key',k)}key.current=k;foods.current=Array.from({length:100},()=>({x:Math.random()*S,y:Math.random()*S}));void load()},[load]);
 useEffect(()=>{const t=setInterval(()=>void load(),3000);return()=>clearInterval(t)},[load]);
 useEffect(()=>{const t=setInterval(()=>void save(),3000);return()=>clearInterval(t)},[save]);
 useEffect(()=>{let closed=false,reconnect:ReturnType<typeof setTimeout>|null=null;const connect=()=>{if(closed)return;setNet('connecting');const ws=new WebSocket(WS);socket.current=ws;ws.onopen=()=>{setNet('connected');send()};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type!=='world'||!Array.isArray(m.worms))return;const seen=new Set<string>();for(const q of m.worms){if(!q?.clientId||q.clientId===key.current)continue;seen.add(q.clientId);const old=remotes.current.get(q.clientId),x=Number(q.x)||0,y=Number(q.y)||0;remotes.current.set(q.clientId,{id:q.clientId,name:q.name||'匿名の芋虫',emoji:q.emoji||'🐛',body:q.body||'🟢',x,y,dir:{x:Number(q.dirX)||0,y:Number(q.dirY)||0},history:old?[{x,y},...old.history].slice(0,MAX):Array.from({length:30},()=>({x,y})),score:Number(q.score)||0,length:Math.max(3,Number(q.length)||3),isAlive:q.isAlive!==false,isNpc:q.isNpc===true,lastSeen:Date.now()})}remotes.current.forEach((_,id)=>{if(!seen.has(id))remotes.current.delete(id)})}catch{}};ws.onclose=()=>{if(!closed){setNet('offline');reconnect=setTimeout(connect,1500)}};ws.onerror=()=>setNet('offline')};connect();return()=>{closed=true;if(reconnect)clearTimeout(reconnect);socket.current?.close()}},[send]);
 useEffect(()=>{const t=setInterval(send,100);return()=>clearInterval(t)},[send]);
 const draw=useCallback((now:number)=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const w=p.current;const rect=c.getBoundingClientRect(),dw=Math.max(1,rect.width),dh=Math.max(1,rect.height),scale=Math.max(dw/S,dh/S)*1.08;const viewW=dw/scale,viewH=dh/scale;const camX=viewW>=S?S/2:Math.max(viewW/2,Math.min(S-viewW/2,w.x)),camY=viewH>=S?S/2:Math.max(viewH/2,Math.min(S-viewH/2,w.y)),ox=dw/2-camX*scale,oy=dh/2-camY*scale;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#a9d9c5';ctx.fillRect(0,0,c.width,c.height);const sx=(x:number)=>x*scale+ox,sy=(y:number)=>y*scale+oy;
  for(const f of foods.current){const fx=sx(f.x),fy=sy(f.y);if(fx>-40&&fx<dw+40&&fy>-40&&fy<dh+40){ctx.font='27px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🥬',fx,fy)}}
  const drawWorm=(q:W,player=false)=>{if(!q.isAlive)return;const seg=Math.min(q.length,q.history.length);for(let i=seg-1;i>=0;i--){const pt=q.history[Math.min(i*SPACING,q.history.length-1)];const x=sx(pt.x),y=sy(pt.y);if(x<-40||x>dw+40||y<-40||y>dh+40)continue;ctx.font='26px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(q.body,x,y)}const ex=player?0:Math.min(120,Math.max(0,now-q.lastSeen))/1000,hx=Math.max(0,Math.min(S,q.x+q.dir.x*3.5*ex)),hy=Math.max(0,Math.min(S,q.y+q.dir.y*3.5*ex));ctx.font='34px sans-serif';ctx.fillText(q.emoji,sx(hx),sy(hy));ctx.font='10px sans-serif';ctx.fillStyle=q.isNpc?'#7b9694':'#466f71';ctx.fillText(`${q.name}${q.isNpc?' · NPC':' · 🌐'}`,sx(hx),sy(hy)-24);ctx.fillStyle='#000'};
  remotes.current.forEach(q=>drawWorm(q));drawWorm(w,true);
 },[]);
 const update=useCallback((now:number)=>{const w=p.current;const dt=lastFrame.current?Math.min(0.033,(now-lastFrame.current)/1000):0;lastFrame.current=now;if(w.isAlive){w.x=Math.max(0,Math.min(S,w.x+w.dir.x*SPEED*(dt*60)));w.y=Math.max(0,Math.min(S,w.y+w.dir.y*SPEED*(dt*60)));w.history.unshift({x:w.x,y:w.y});if(w.history.length>MAX)w.history.pop();let next:P[]=[],eat=0;for(const f of foods.current){if(Math.hypot(f.x-w.x,f.y-w.y)<FOOD)eat++;else next.push(f)}if(eat){w.score+=eat;w.length=3+Math.floor(w.score/5);setScore(w.score)}foods.current=next;let hit=false;remotes.current.forEach(o=>{if(hit||!o.isAlive)return;for(let i=0;i<o.history.length&&i<o.length*SPACING;i+=SPACING)if(Math.hypot(w.x-o.history[i].x,w.y-o.history[i].y)<HIT){hit=true;break}});if(hit){w.isAlive=false;setState('gameover');void save()}}draw(now);raf.current=requestAnimationFrame(update)},[draw,save]);
 useEffect(()=>{raf.current=requestAnimationFrame(update);return()=>cancelAnimationFrame(raf.current)},[update]);
 const move=useCallback((x:number,y:number)=>{const r=box.current?.getBoundingClientRect();if(!r)return;const dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),d=Math.hypot(dx,dy);if(d>10)p.current.dir={x:dx/d,y:dy/d}},[]);
 useEffect(()=>{const m=(e:MouseEvent)=>move(e.clientX,e.clientY),t=(e:TouchEvent)=>e.touches[0]&&move(e.touches[0].clientX,e.touches[0].clientY),k=(e:KeyboardEvent)=>{const d:Record<string,P>={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}};if(d[e.key]){e.preventDefault();p.current.dir=d[e.key]}};window.addEventListener('mousemove',m);window.addEventListener('touchmove',t,{passive:true});window.addEventListener('keydown',k);return()=>{window.removeEventListener('mousemove',m);window.removeEventListener('touchmove',t);window.removeEventListener('keydown',k)}},[move]);
 const respawn=()=>{p.current=makePlayer(nickname);setScore(0);setState('playing');void send()};
 const humans=Array.from(remotes.current.values()).filter(w=>!w.isNpc).length+1,npcCount=Array.from(remotes.current.values()).filter(w=>w.isNpc).length;
 return <section className="activity-section game-page"><p className="eyebrow">WORM BEACH</p><h2>芋虫浜 <small className="score-label">🥬 {score} <span style={{opacity:.7,fontSize:'.9em'}}>({score%5}/5で🟢)</span></small></h2><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:8,fontSize:10,color:'#6f8d86'}}><span>{net==='connected'?'🟢 オンライン':net==='connecting'?'🟡 接続中…':'⚪ 再接続中…'}</span><span>👥 {humans}人 / NPC {npcCount}匹</span></div>
 <div ref={box} className="worm-game" style={{position:'relative',width:'100%',height:450,overflow:'hidden',background:'#a9d9c5',borderRadius:'12px 30px 30px 30px',touchAction:'none'}}><canvas ref={canvas} width={900} height={450} style={{display:'block',width:'100%',height:'100%'}}/>{state==='playing'&&<p style={{position:'absolute',bottom:16,left:20,margin:0,zIndex:20,color:'#57877c',fontSize:9,pointerEvents:'none'}}>画面をタップした方向、または矢印キーで移動 · 他の芋虫の体に頭がぶつかると消滅</p>}{state==='gameover'&&<div style={{position:'absolute',inset:0,background:'rgba(34,56,62,.5)',display:'grid',placeItems:'center',zIndex:100}}><div style={{background:'#fffaf1',padding:'30px 40px',borderRadius:16,textAlign:'center'}}><h3>観測終了</h3><p>集めたキャベツ: <b>{score}</b></p><button className="pick-button" onClick={respawn}>もう一度遊ぶ</button></div></div>}</div>
 <div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:15,alignItems:'start',marginTop:15}}><div style={{minWidth:0}}><h3 style={{margin:'0 0 8px',color:'#466f71',fontSize:15}}>🏆 芋虫浜ランキング <small style={{fontWeight:'normal',opacity:.65}}>全参加者</small></h3><div style={{display:'grid',gap:4,fontSize:11,color:'#6f8d86'}}>{ranking.length===0&&<span>まだ記録がありません。最初の芋虫になろう。</span>}{ranking.map((r,i)=><div key={`${r.nickname}-${i}`} style={{display:'grid',gridTemplateColumns:'28px minmax(0,1fr) auto',gap:6,alignItems:'center',padding:'5px 7px',borderRadius:7,background:i===0?'rgba(255,242,185,.55)':'rgba(255,255,255,.45)',minWidth:0}}><span>{i+1}.</span><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.nickname}</span><b style={{whiteSpace:'nowrap'}}>{r.score} 🥬</b></div>)}</div></div><div style={{display:'flex',gap:10,flexWrap:'wrap',justifyContent:'flex-end'}}><button className="play-button" onClick={onExit}>← 広場へ戻る</button><button className="ghost-button" onClick={()=>setRules(true)}>？ ルール</button><button className="ghost-button" style={{color:'#d87070'}} onClick={()=>{p.current.isAlive=false;void save();setState('gameover')}}>退出して共有</button></div></div>
 {rules&&<div className="modal-backdrop" onClick={()=>setRules(false)}><div className="detail-modal" style={{width:'min(100%,400px)'}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setRules(false)}><X size={18}/></button><p className="eyebrow">RULES</p><h2>芋虫浜の歩き方</h2><ul style={{color:'#7b9694',fontSize:12,lineHeight:2}}><li>🥬を食べるとスコアが上がり、5つごとに体が長くなります。</li><li>他の芋虫の体に頭がぶつかると消滅します。</li><li>NPCは人がいなくてもサーバー上で動き続けます。</li><li>ランキングはNPCとプレイヤーをまとめて表示します。</li></ul><button className="primary-button" style={{width:'100%',justifyContent:'center'}} onClick={()=>setRules(false)}>閉じる</button></div></div>}</section>;
}
